// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class ChatMessage
{
    public long ChatMessageId { get; set; }

    public long ChatRoomId { get; set; }

    public Guid SenderId { get; set; }

    public string MessageText { get; set; }

    public bool? IsRead { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ChatRoom ChatRoom { get; set; }

    public virtual User Sender { get; set; }
}