// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Notification
{
    public long NotificationId { get; set; }

    public Guid? UserId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Type { get; set; }

    public bool? IsRead { get; set; }

    public string TargetType { get; set; }

    public string TargetId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User User { get; set; }
}