// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class ProductVariant
{
    public long ProductVariantId { get; set; }

    public long ProductId { get; set; }

    public string Color { get; set; }

    public string Storage { get; set; }

    public decimal OriginalPrice { get; set; }

    public int? DiscountPercentage { get; set; }

    public decimal SalePrice { get; set; }

    public int? StockQuantity { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Product Product { get; set; }
}